map file add and embedding of the map in app
Amustache/SecCom pull request #30
Opened 2024-10-16 17:25 UTC by matthieujacques

Hello, j'ai donc ramené mon fichier map.py depuis ma branch, j'ai ensuite mis toutes les fonctions dont je me servais dans une fonction qui créé l'ensemble de la carte pour l'utiliser dans app.py pour afficher. Malheureusement, je n'arrive pas à voir la carte qui devrait s'afficher au port http://localhost:8888/map

2024-10-22 10:30 UTC, Amustache commented
Il manque des geojson hardcodés : `FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Admin/OneDrive/Documents/GitHub/SecCom/data/lakes.json'`

2024-10-22 10:50 UTC, Amustache requested changes

2024-10-22 17:20 UTC, matthieujacques commented
![page_accueil](https://github.com/user-attachments/assets/72b4fa55-7b11-47bd-90c2-0fdd3303150f)
![quest_glob_main](https://github.com/user-attachments/assets/df77f143-8ec9-4947-8037-90551438f1a5)
![quest_glob_slider](https://github.com/user-attachments/assets/1307cb75-dae9-424c-a636-37aa8d16c1fc)
![survey](https://github.com/user-attachments/assets/32a07498-a10b-443c-82ce-ffe5b0c5d8e4)
Voici différentes captures d'écran. Pour le moment, la legende (color scale bar) pose problème mais je vais regarder pour résoudre ça pour la suite. 
Le slider pour les questions globales (utilisé pour afficher la longitudanilité) n'est pas encore fonctionnel mais c'est en cours.

2024-10-23 07:37 UTC, Amustache commented on webapp/app.py
> +    from config.py.dist import SERVER_HOST, SERVER_PORT
```suggestion
    from config import SERVER_HOST, SERVER_PORT

```

2024-10-23 10:48 UTC, Amustache commented on webapp/app.py
> +    app = create_dash_app(app)
En gros c'est ici que la magie s'opère : je prends mon application _Flask_ existante, que je passe en paramètre à la fonction pour créer l'application _Dash_, je paramètre l'application _Dash_ dans mon application _Flask_, et je retourne mon application _Flask_.

2024-10-23 10:53 UTC, Amustache requested changes

2024-10-23 10:53 UTC, Amustache commented on webapp/map.py
> +    # Create a Dash app
Faudra nettoyer ton code pour enlever tout ce qui n'est pas explicitement utilisé.

2024-10-23 10:53 UTC, Amustache commented on webapp/map.py
> +                top_10_question_globales["code_first_question"].isin(df_commune_responses.columns)
J'arrive pas à accéder aux questions globales :
![image](https://github.com/user-attachments/assets/475b6cf7-349c-4780-8cc1-d15ebd00974f)

2024-10-23 10:53 UTC, Amustache commented on webapp/map.py
> +        communes = filtered_responses["GSB23_Q100"].astype(int).tolist()
Bugs sur la sélection des questions
![image](https://github.com/user-attachments/assets/6fc30147-4947-4821-b0c5-c59af24edac8)
![image](https://github.com/user-attachments/assets/7e7bb1e2-fa6c-4fac-9d1e-25032142b0a4)

2024-10-23 10:53 UTC, Amustache commented on webapp/map.py
> +            html.H1(id="page-title", style={"text-align": "left", "margin-bottom": "40px"}),
Pour le layout faudra l'intégrer joliment quelque part - ça à la limite on fait la semaine prochaine pour l'instant priorité fonctionnel.

2024-10-23 17:04 UTC, matthieujacques commented on webapp/map.py
> +                top_10_question_globales["code_first_question"].isin(df_commune_responses.columns)
j'arrive pas à reproduire cette erreur, on pourra regarder la semaine prochaine, chez moi ça fonctionne 
![image](https://github.com/user-attachments/assets/88eaa7b9-f59e-4473-bb31-5fec18b11185)

2024-10-23 17:05 UTC, matthieujacques commented on webapp/map.py
> +    # Create a Dash app
yes, une fois le slider fonctionnel avec les questions globales des autres années je vais essayer de supprimer tous les df inutiles

2024-10-23 17:14 UTC, matthieujacques commented on webapp/map.py
> +        communes = filtered_responses["GSB23_Q100"].astype(int).tolist()
Pour ça, j'ai modifié la fonction create_figure pour ajouter une condition dans  la boucle pour unique_values : unique_values = [v for v in variable_values if isinstance(v, (int, float)) and v != -99 and not np.isnan(v)]
isinstance(v, (int, float)) assure que v est soit un int soit un float --> plus de problème d'erreur normalement

2024-10-29 11:49 UTC, Amustache requested changes

2024-10-29 11:49 UTC, Amustache commented on webapp/map.py
> +    #print('response old years',df_commune_response_old_year.head())
Nettoyer les prints plutôt que de les laisser en commentaire

2024-10-29 11:49 UTC, Amustache commented on webapp/map.py
>      df_commune_responses = pd.read_csv("data/commune_responses.csv")
Idéalement, `os.path.join(BASE_DIR, "ton truc")`, pour éviter les soucis

2024-10-29 11:49 UTC, Amustache commented on webapp/map.py
> +    #print('response full years',df_commune_responses_combined.head())
Pareil nettoyer tout ce qui est print/commentaires par utiles

2024-11-19 09:18 UTC, closed without merging